// prescription types
export const CREATE_PRESCRIPTION = "CREATE_PRESCRIPTION";
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";
export const GET_PRESCRIPTION = "GET_PRESCRIPTION";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const ADD_FORMULA = "ADD_FORMULA";
export const GET_PRESCRIPTION_BY_ID = "GET_PRESCRIPTION_BY_ID";
export const GET_FORMULA = "GET_FORMULA";
export const NO_FORMULA ="NO_FORMULA";
export const FETCH_PRESCRIPTION_START = "FETCH_PRESCRIPTION_START";
