// prescription types
export const CREATE_PRESCRIPTION = "CREATE_PRESCRIPTION";
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";
export const GET_PRESCRIPTION = "GET_PRESCRIPTION";
export const INPUT_CHANGE = "INPUT_CHANGE";
